export const LANG_META = {
  pt: { flag: '🇧🇷', label: 'Português', locale: 'pt-BR' },
  en: { flag: '🇬🇧', label: 'English', locale: 'en-GB' },
  es: { flag: '🇪🇸', label: 'Español', locale: 'es-ES' },
};

export const TEXT = {
  pt: {
    subtitle: '🌎 um atlas 3D cheio de surpresas', hint: 'Passe o mouse em um país para descobrir segredos!',
    home: '🏠 Início', spin: '🌀 Girar', stopSpin: '⏸ Parar giro', homeTitle: 'Voltar para a visão inicial', spinTitle: 'Girar o globo sozinho', menu: '🗺️ Menu', menuTitle: 'Voltar ao menu de aventuras',
    sheet: '✨ ficha do país', capital: 'Capital', population: 'População', size: 'Tamanho', region: 'Região',
    curiosities: '🎈 Curiosidades', places: '📸 Lugares para conhecer', speak: '🔊 Ouvir em voz alta', stop: '⏹ Parar',
    worldTitle: 'O Mundo da {brand}', namePrompt: 'Como você se chama?', nameText: 'Digite seu nome para começar a aventura.', nameLabel: 'Seu nome', namePlaceholder: 'Escreva seu nome', introTitle: 'Olá, {name}!', introText: 'Que bom ter você no <b>Mundo da {brand}</b>!<br>Arraste para girar o planeta, role para chegar pertinho e passe o mouse nos países para descobrir curiosidades incríveis!', introButton: 'Começar a aventura 🚀', introLanguage: '🌐 Escolha seu idioma',
    ranking: '🏆 Ranking', rankingOpen: 'Abrir ranking', rankingClose: 'Fechar ranking', switchPlayer: 'Trocar explorador', badges: 'Badges conquistados', stickersTitle: '🎟️ Álbum de stickers', stickerSummary: '{total} stickers · {places} lugares + {bonus} bônus', stickerEmpty: 'Abra um lugar para ganhar seu primeiro sticker.', stickerOpen: 'Abrir {place} na Wikipedia', stickerBonus: 'Sticker bônus', continentProgress: 'Progresso por continente', leaderboard: 'Exploradores', noBadges: 'Explore países e lugares para ganhar seu primeiro badge.', noRanking: 'Visite um país para entrar no ranking.', score: '{points} pontos', countriesVisited: '{visited}/{total} países', placesProgress: '{visited}/{total} lugares', placesVisited: '{count} lugares', rankYou: 'Você', badgeContinent: 'Explorador de {continent}', badgeMini: 'Mini explorador', badgeSilver: 'Explorador prata', badgeGold: 'Explorador ouro', badgeSuper: 'Super explorador', continentAfrica: 'África', continentNorthAmerica: 'América do Norte', continentSouthAmerica: 'América do Sul', continentAsia: 'Ásia', continentEurope: 'Europa', continentOceania: 'Oceania', continentAntarctica: 'Antártida',
    modalFallback: 'Conheça {place}!', wiki: 'Ver mais na Wikipedia ↗', modalLabel: 'Foto do lugar',
    settings: '⚙️ Configurações', close: 'Fechar', language: '🌐 Idioma', theme: '🎨 Cores do ambiente', themeHelp: 'Automático muda o céu conforme a hora do computador.', accent: '✨ Cor do destaque', saved: '💾 Suas escolhas ficam salvas neste computador.', themeStatus: 'Agora: {theme}.', themeAuto: '⏰ Automático por hora', themeDay: '☀️ Dia ensolarado', themeSunset: '🌇 Pôr do sol', themeNight: '🌙 Noite espacial',
    helpButton: '❓ Help', helpTitle: '❓ Como usar o atlas', helpClose: 'Fechar ajuda', helpIntro: 'Descubra como explorar o mundo, colecionar stickers e conquistar badges.', helpExploreTitle: '🌍 Explorar o mundo', helpExploreText: 'Arraste o globo para girar, use a roda do mouse para chegar mais perto e clique em um país para abrir sua ficha.', helpControlsTitle: '🖱️ Controles rápidos', helpControlsText: 'Use Início para voltar à visão inicial, Girar para deixar o planeta rodando e o menu ☰ para abrir as configurações e esta ajuda.', helpStickersTitle: '🎟️ Stickers', helpStickersText: 'Cada lugar aberto dá 1 sticker com link para a Wikipedia. Ao visitar 10 lugares, você ganha +5 stickers; ao chegar a 50, ganha +20 adicionais, além do bônus anterior.', helpBadgesTitle: '🏅 Badges', helpBadgesText: 'Complete todos os países de um continente para ganhar seu badge. Também existem badges por 5, 25 e 75 lugares, além do Super explorador ao visitar todos os países.', helpRankingTitle: '🏆 Ranking', helpRankingText: 'Você ganha 3 pontos por lugar e 100 pontos por badge. Trocar explorador permite registrar várias pessoas; os perfis ficam salvos neste computador.',
    aboutButton: 'ℹ️ About', aboutTitle: 'ℹ️ Sobre este projeto', aboutClose: 'Fechar About', aboutIntro: 'Julia’s World é um projeto feito pela Julia com o pai, Marcelo.', aboutStoryTitle: '💛 Uma ideia para fazer juntos', aboutStoryText: 'Nós dois queríamos uma atividade para fazer juntos. Por isso, escolhemos criar apps com inteligência artificial e transformar essa ideia em um mundo para explorar.', aboutCreatorsTitle: '👩‍💻👨‍💻 Julia e Marcelo', aboutCreatorsText: 'Este app é resultado do trabalho conjunto dos dois.', aboutAITitle: '✨ Criando com IA', aboutAIText: 'A inteligência artificial foi usada como uma ferramenta de criação para ajudar a transformar as ideias deles em apps.',
    advPanel: 'Aventuras', advTaskCountries: 'Visite {target} países', advTaskAudio: 'Ouça o áudio de {target} países', advTaskPlaces: 'Descubra {target} lugares', advTaskWiki: 'Abra {target} links da Wikipedia', advTaskContinents: 'Visite países em {target} continentes', advTaskContinentComplete: 'Complete: {continent}', advTaskWorld: 'Visite todos os países', advCelebrateTitle: 'Tarefa completa!', advTapPresent: 'Toque no presente!', advCertificate: 'Certificado de Exploração', advCongrats: 'Parabéns!', advCertFor: '{name} completou a tarefa', advRewardStickers: '+{n} stickers', advRewardBadge: '+{n} badges', advMilestoneBadge: 'Marco: {n} tarefas', advContinue: 'Continuar', advMilestoneTitle: 'Marco da aventura!', advCountries: '{n}/{total} países', advWorldTitle: 'Você completou a Aventura do Mundo!', advReturnToMenu: 'Voltar ao menu', advFinalHint: 'Abra seus prêmios em ordem!', advPresentN: 'Prêmio {n} de {total}', advTapChest: 'Toque no baú!', advTasksCompleted: '{n} tarefas concluídas',
  },
  en: {
    subtitle: '🌎 a 3D atlas full of surprises', hint: 'Hover over a country to discover secrets!',
    home: '🏠 Home', spin: '🌀 Spin', stopSpin: '⏸ Stop spinning', homeTitle: 'Return to the starting view', spinTitle: 'Spin the globe automatically', menu: '🗺️ Menu', menuTitle: 'Back to the adventures menu',
    sheet: '✨ country card', capital: 'Capital', population: 'Population', size: 'Size', region: 'Region',
    curiosities: '🎈 Fun facts', places: '📸 Places to visit', speak: '🔊 Listen out loud', stop: '⏹ Stop',
    worldTitle: '{brand}\'s World', namePrompt: 'What is your name?', nameText: 'Tell us your name to begin the adventure.', nameLabel: 'Your name', namePlaceholder: 'Type your name', introTitle: 'Hello, {name}!', introText: 'Welcome to <b>{brand}\'s World</b>!<br>Drag to spin the planet, scroll to zoom in and hover over countries to discover amazing facts!', introButton: 'Start the adventure 🚀', introLanguage: '🌐 Choose your language',
    ranking: '🏆 Leaderboard', rankingOpen: 'Open leaderboard', rankingClose: 'Close leaderboard', switchPlayer: 'Switch explorer', badges: 'Badges earned', stickersTitle: '🎟️ Sticker album', stickerSummary: '{total} stickers · {places} places + {bonus} bonus', stickerEmpty: 'Open a place to earn your first sticker.', stickerOpen: 'Open {place} on Wikipedia', stickerBonus: 'Bonus sticker', continentProgress: 'Progress by continent', leaderboard: 'Explorers', noBadges: 'Explore countries and places to earn your first badge.', noRanking: 'Visit a country to join the leaderboard.', score: '{points} points', countriesVisited: '{visited}/{total} countries', placesProgress: '{visited}/{total} places', placesVisited: '{count} places', rankYou: 'You', badgeContinent: '{continent} explorer', badgeMini: 'Mini Explorer', badgeSilver: 'Silver Explorer', badgeGold: 'Gold Explorer', badgeSuper: 'Super Explorer', continentAfrica: 'Africa', continentNorthAmerica: 'North America', continentSouthAmerica: 'South America', continentAsia: 'Asia', continentEurope: 'Europe', continentOceania: 'Oceania', continentAntarctica: 'Antarctica',
    modalFallback: 'Discover {place}!', wiki: 'See more on Wikipedia ↗', modalLabel: 'Place photo',
    settings: '⚙️ Settings', close: 'Close', language: '🌐 Language', theme: '🎨 Environment colors', themeHelp: 'Automatic changes the sky according to your computer time.', accent: '✨ Highlight color', saved: '💾 Your choices are saved on this computer.', themeStatus: 'Now: {theme}.', themeAuto: '⏰ Automatic by time', themeDay: '☀️ Sunny day', themeSunset: '🌇 Sunset', themeNight: '🌙 Space night',
    helpButton: '❓ Help', helpTitle: '❓ How to use the atlas', helpClose: 'Close help', helpIntro: 'Learn how to explore the world, collect stickers and earn badges.', helpExploreTitle: '🌍 Explore the world', helpExploreText: 'Drag the globe to spin it, use the mouse wheel to zoom and click a country to open its card.', helpControlsTitle: '🖱️ Quick controls', helpControlsText: 'Use Home to return to the starting view, Spin to keep the planet moving and the ☰ menu to open settings and this help.', helpStickersTitle: '🎟️ Stickers', helpStickersText: 'Each place you open gives you 1 sticker with a Wikipedia link. At 10 places you get +5 stickers; at 50 you get +20 more, in addition to the earlier bonus.', helpBadgesTitle: '🏅 Badges', helpBadgesText: 'Complete every country in a continent to earn its badge. There are also badges for 5, 25 and 75 places, plus Super Explorer for visiting every country.', helpRankingTitle: '🏆 Leaderboard', helpRankingText: 'You get 3 points per place and 100 points per badge. Switch explorer to record several people; profiles are saved on this computer.',
    aboutButton: 'ℹ️ About', aboutTitle: 'ℹ️ About this project', aboutClose: 'Close About', aboutIntro: 'Julia’s World is a project made by Julia and her father, Marcelo.', aboutStoryTitle: '💛 An activity to do together', aboutStoryText: 'They wanted an activity they could do together, so they chose to create apps with artificial intelligence and turn that idea into a world to explore.', aboutCreatorsTitle: '👩‍💻👨‍💻 Julia and Marcelo', aboutCreatorsText: 'This app is the result of their work together.', aboutAITitle: '✨ Creating with AI', aboutAIText: 'Artificial intelligence was used as a creative tool to help turn their ideas into apps.',
    advPanel: 'Adventures', advTaskCountries: 'Visit {target} countries', advTaskAudio: 'Listen to {target} countries out loud', advTaskPlaces: 'Discover {target} places', advTaskWiki: 'Open {target} Wikipedia links', advTaskContinents: 'Visit countries on {target} continents', advTaskContinentComplete: 'Complete: {continent}', advTaskWorld: 'Visit every country', advCelebrateTitle: 'Task complete!', advTapPresent: 'Tap the present!', advCertificate: 'Certificate of Exploration', advCongrats: 'Congratulations!', advCertFor: '{name} completed the task', advRewardStickers: '+{n} stickers', advRewardBadge: '+{n} badges', advMilestoneBadge: 'Milestone: {n} tasks', advContinue: 'Continue', advMilestoneTitle: 'Adventure milestone!', advCountries: '{n}/{total} countries', advWorldTitle: 'You completed the World Adventure!', advReturnToMenu: 'Return to Menu', advFinalHint: 'Open your prizes in order!', advPresentN: 'Present {n} of {total}', advTapChest: 'Tap the chest!', advTasksCompleted: '{n} tasks completed',
  },
  es: {
    subtitle: '🌎 un atlas 3D lleno de sorpresas', hint: '¡Pasa el mouse por un país y descubre secretos!',
    home: '🏠 Inicio', spin: '🌀 Girar', stopSpin: '⏸ Parar giro', homeTitle: 'Volver a la vista inicial', spinTitle: 'Girar el globo automáticamente', menu: '🗺️ Menú', menuTitle: 'Volver al menú de aventuras',
    sheet: '✨ ficha del país', capital: 'Capital', population: 'Población', size: 'Tamaño', region: 'Región',
    curiosities: '🎈 Curiosidades', places: '📸 Lugares para conocer', speak: '🔊 Escuchar en voz alta', stop: '⏹ Parar',
    worldTitle: 'El Mundo de {brand}', namePrompt: '¿Cómo te llamas?', nameText: 'Escribe tu nombre para comenzar la aventura.', nameLabel: 'Tu nombre', namePlaceholder: 'Escribe tu nombre', introTitle: '¡Hola, {name}!', introText: '¡Qué bueno tenerte en el <b>Mundo de {brand}</b>!<br>Arrastra para girar el planeta, usa la rueda para acercarte y pasa el mouse por los países para descubrir curiosidades increíbles!', introButton: 'Comenzar la aventura 🚀', introLanguage: '🌐 Elige tu idioma',
    ranking: '🏆 Ranking', rankingOpen: 'Abrir ranking', rankingClose: 'Cerrar ranking', switchPlayer: 'Cambiar explorador', badges: 'Badges ganados', stickersTitle: '🎟️ Álbum de stickers', stickerSummary: '{total} stickers · {places} lugares + {bonus} bonus', stickerEmpty: 'Abre un lugar para ganar tu primer sticker.', stickerOpen: 'Abrir {place} en Wikipedia', stickerBonus: 'Sticker bonus', continentProgress: 'Progreso por continente', leaderboard: 'Exploradores', noBadges: 'Explora países y lugares para ganar tu primer badge.', noRanking: 'Visita un país para entrar al ranking.', score: '{points} puntos', countriesVisited: '{visited}/{total} países', placesProgress: '{visited}/{total} lugares', placesVisited: '{count} lugares', rankYou: 'Tú', badgeContinent: 'Explorador de {continent}', badgeMini: 'Mini explorador', badgeSilver: 'Explorador de plata', badgeGold: 'Explorador de oro', badgeSuper: 'Super explorador', continentAfrica: 'África', continentNorthAmerica: 'Norteamérica', continentSouthAmerica: 'Sudamérica', continentAsia: 'Asia', continentEurope: 'Europa', continentOceania: 'Oceanía', continentAntarctica: 'Antártida',
    modalFallback: '¡Conoce {place}!', wiki: 'Ver más en Wikipedia ↗', modalLabel: 'Foto del lugar',
    settings: '⚙️ Configuración', close: 'Cerrar', language: '🌐 Idioma', theme: '🎨 Colores del ambiente', themeHelp: 'Automático cambia el cielo según la hora de tu computadora.', accent: '✨ Color destacado', saved: '💾 Tus elecciones quedan guardadas en esta computadora.', themeStatus: 'Ahora: {theme}.', themeAuto: '⏰ Automático por hora', themeDay: '☀️ Día soleado', themeSunset: '🌇 Atardecer', themeNight: '🌙 Noche espacial',
    helpButton: '❓ Ayuda', helpTitle: '❓ Cómo usar el atlas', helpClose: 'Cerrar ayuda', helpIntro: 'Descubre cómo explorar el mundo, coleccionar stickers y ganar badges.', helpExploreTitle: '🌍 Explorar el mundo', helpExploreText: 'Arrastra el globo para girarlo, usa la rueda del mouse para acercarte y haz clic en un país para abrir su ficha.', helpControlsTitle: '🖱️ Controles rápidos', helpControlsText: 'Usa Inicio para volver a la vista inicial, Girar para mantener el planeta en movimiento y el menú ☰ para abrir la configuración y esta ayuda.', helpStickersTitle: '🎟️ Stickers', helpStickersText: 'Cada lugar que abras te da 1 sticker con enlace a Wikipedia. Al visitar 10 lugares ganas +5 stickers; al llegar a 50 ganas +20 adicionales, además del bono anterior.', helpBadgesTitle: '🏅 Badges', helpBadgesText: 'Completa todos los países de un continente para ganar su badge. También hay badges por 5, 25 y 75 lugares, además del Super explorador al visitar todos los países.', helpRankingTitle: '🏆 Ranking', helpRankingText: 'Ganas 3 puntos por lugar y 100 puntos por badge. Cambiar de explorador permite registrar varias personas; los perfiles se guardan en este computador.',
    aboutButton: 'ℹ️ About', aboutTitle: 'ℹ️ Sobre este proyecto', aboutClose: 'Cerrar About', aboutIntro: 'Julia’s World es un proyecto hecho por Julia y su padre, Marcelo.', aboutStoryTitle: '💛 Una actividad para hacer juntos', aboutStoryText: 'Querían una actividad para hacer juntos, así que eligieron crear apps con inteligencia artificial y convertir esa idea en un mundo para explorar.', aboutCreatorsTitle: '👩‍💻👨‍💻 Julia y Marcelo', aboutCreatorsText: 'Esta app es el resultado del trabajo conjunto de los dos.', aboutAITitle: '✨ Creando con IA', aboutAIText: 'La inteligencia artificial se usó como una herramienta creativa para ayudar a convertir sus ideas en apps.',
    advPanel: 'Aventuras', advTaskCountries: 'Visita {target} países', advTaskAudio: 'Escucha el audio de {target} países', advTaskPlaces: 'Descubre {target} lugares', advTaskWiki: 'Abre {target} enlaces de Wikipedia', advTaskContinents: 'Visita países de {target} continentes', advTaskContinentComplete: 'Completa: {continent}', advTaskWorld: 'Visita todos los países', advCelebrateTitle: '¡Tarea completada!', advTapPresent: '¡Toca el regalo!', advCertificate: 'Certificado de Exploración', advCongrats: '¡Felicitaciones!', advCertFor: '{name} completó la tarea', advRewardStickers: '+{n} stickers', advRewardBadge: '+{n} badges', advMilestoneBadge: 'Hito: {n} tareas', advContinue: 'Continuar', advMilestoneTitle: '¡Hito de la aventura!', advCountries: '{n}/{total} países', advWorldTitle: '¡Completaste la Aventura del Mundo!', advReturnToMenu: 'Volver al menú', advFinalHint: '¡Abre tus premios en orden!', advPresentN: 'Premio {n} de {total}', advTapChest: '¡Toca el cofre!', advTasksCompleted: '{n} tareas completadas',
  },
};

export function text(language, key, vars = {}) {
  let value = TEXT[language]?.[key] ?? TEXT.pt[key] ?? key;
  for (const [name, replacement] of Object.entries(vars)) value = value.replaceAll(`{${name}}`, replacement);
  return value;
}
