// Bancos de dados lexicais do English Adventures (inglês britânico).
// Cada entrada é usada para gerar questões Quest/Bexley-style com
// distratores plausíveis. tier: 1-3 easy, 4-6 medium, 7-9 hard,
// 10-12 very hard, 13-15 very very hard (progressão da Julia).

export const SYNONYMS = [
  { w: 'happy', tier: 1, s: ['cheerful', 'joyful', 'merry', 'glad'], d: ['tired', 'quiet', 'brave'] },
  { w: 'big', tier: 1, s: ['huge', 'enormous', 'giant', 'vast'], d: ['tiny', 'narrow', 'soft'] },
  { w: 'sad', tier: 1, s: ['unhappy', 'gloomy', 'miserable'], d: ['sunny', 'kind', 'loud'] },
  { w: 'fast', tier: 1, s: ['quick', 'rapid', 'swift', 'speedy'], d: ['slow', 'heavy', 'calm'] },
  { w: 'scared', tier: 1, s: ['frightened', 'afraid', 'terrified'], d: ['curious', 'proud', 'sleepy'] },
  { w: 'pretty', tier: 1, s: ['beautiful', 'lovely', 'gorgeous'], d: ['messy', 'plain', 'strong'] },
  { w: 'smart', tier: 2, s: ['clever', 'bright', 'wise', 'brainy'], d: ['silly', 'kind', 'brave'] },
  { w: 'angry', tier: 2, s: ['furious', 'cross', 'annoyed', 'irate'], d: ['calm', 'glad', 'shy'] },
  { w: 'cold', tier: 2, s: ['freezing', 'chilly', 'icy', 'frosty'], d: ['warm', 'cosy', 'damp'] },
  { w: 'look', tier: 2, s: ['glance', 'gaze', 'stare', 'peek'], d: ['listen', 'walk', 'grab'] },
  { w: 'tired', tier: 2, s: ['exhausted', 'weary', 'sleepy', 'worn out'], d: ['fresh', 'loud', 'strict'] },
  { w: 'nice', tier: 2, s: ['kind', 'pleasant', 'friendly', 'lovely'], d: ['rude', 'sharp', 'odd'] },
  { w: 'begin', tier: 3, s: ['start', 'commence', 'launch'], d: ['finish', 'pause', 'end'] },
  { w: 'brave', tier: 3, s: ['courageous', 'bold', 'fearless', 'daring'], d: ['timid', 'careless', 'clever'] },
  { w: 'shout', tier: 3, s: ['yell', 'bellow', 'roar', 'holler'], d: ['whisper', 'mutter', 'sing'] },
  { w: 'strange', tier: 3, s: ['odd', 'peculiar', 'unusual', 'bizarre'], d: ['normal', 'plain', 'silly'] },
  { w: 'help', tier: 3, s: ['assist', 'aid', 'support'], d: ['block', 'watch', 'copy'] },
  { w: 'walk', tier: 3, s: ['stroll', 'wander', 'amble', 'march'], d: ['run', 'sit', 'crawl'] },
  { w: 'important', tier: 4, s: ['significant', 'crucial', 'vital', 'essential'], d: ['trivial', 'minor', 'plain'] },
  { w: 'problem', tier: 4, s: ['issue', 'difficulty', 'trouble', 'dilemma'], d: ['solution', 'answer', 'game'] },
  { w: 'brave', tier: 4, s: ['valiant', 'gallant', 'heroic'], d: ['timid', 'reckless', 'weary'] },
  { w: 'wet', tier: 4, s: ['damp', 'soaked', 'drenched', 'soggy'], d: ['arid', 'warm', 'crisp'] },
  { w: 'old', tier: 4, s: ['ancient', 'elderly', 'aged', 'antique'], d: ['brand new', 'modern', 'young'] },
  { w: 'hide', tier: 4, s: ['conceal', 'cover', 'tuck away'], d: ['reveal', 'display', 'seek'] },
  { w: 'angry', tier: 5, s: ['livid', 'incensed', 'outraged'], d: ['pleased', 'soothed', 'gentle'] },
  { w: 'happy', tier: 5, s: ['elated', 'overjoyed', 'delighted', 'thrilled'], d: ['downcast', 'glum', 'weary'] },
  { w: 'sad', tier: 5, s: ['downcast', 'dejected', 'sorrowful', 'crestfallen'], d: ['cheerful', 'bright', 'buoyant'] },
  { w: 'big', tier: 5, s: ['colossal', 'immense', 'towering', 'mammoth'], d: ['minute', 'petite', 'cramped'] },
  { w: 'strange', tier: 5, s: ['peculiar', 'baffling', 'surreal'], d: ['ordinary', 'familiar', 'expected'] },
  { w: 'quiet', tier: 6, s: ['hushed', 'silent', 'soundless', 'still'], d: ['deafening', 'clamorous', 'rowdy'] },
  { w: 'shiny', tier: 6, s: ['gleaming', 'glistening', 'polished', 'lustrous'], d: ['dull', 'tarnished', 'matte'] },
  { w: 'clever', tier: 6, s: ['ingenious', 'shrewd', 'astute'], d: ['foolish', 'oblivious', 'naive'] },
  { w: 'excited', tier: 6, s: ['thrilled', 'exhilarated', 'eager'], d: ['indifferent', 'bored', 'reluctant'] },
  { w: 'look', tier: 7, s: ['examine', 'inspect', 'scrutinise', 'observe'], d: ['overlook', 'ignore', 'skim'] },
  { w: 'brave', tier: 8, s: ['intrepid', 'audacious', 'undaunted'], d: ['craven', 'hesitant', 'faint-hearted'] },
  { w: 'strange', tier: 8, s: ['peculiar', 'inexplicable', 'uncanny'], d: ['conventional', 'predictable', 'prosaic'] },
  { w: 'happy', tier: 9, s: ['elated', 'jubilant', 'euphoric'], d: ['despondent', 'morose', 'lugubrious'] },
  { w: 'angry', tier: 9, s: ['indignant', 'incandescent', 'apoplectic'], d: ['placated', 'appeased', 'serene'] },
  { w: 'big', tier: 10, s: ['gargantuan', 'monumental', 'immeasurable'], d: ['infinitesimal', 'modest', 'minute'] },
  { w: 'clever', tier: 10, s: ['erudite', 'perceptive', 'discerning'], d: ['obtuse', 'shallow', 'heedless'] },
  { w: 'sad', tier: 11, s: ['melancholy', 'desolate', 'forlorn'], d: ['elated', 'radiant', 'buoyant'] },
  { w: 'quiet', tier: 11, s: ['inaudible', 'muted', 'unobtrusive'], d: ['thunderous', 'vociferous', 'clamorous'] },
  { w: 'eager', tier: 12, s: ['zealous', 'avid', 'ardent'], d: ['apathetic', 'loath', 'disinclined'] },
  { w: 'strange', tier: 13, s: ['anomalous', 'esoteric', 'arcane'], d: ['ubiquitous', 'orthodox', 'hackneyed'] },
  { w: 'brave', tier: 14, s: ['dauntless', 'lionhearted', 'valorous'], d: ['pusillanimous', 'dithering', 'lily-livered'] },
  { w: 'happy', tier: 15, s: ['blissful', 'contented', 'radiant'], d: ['despairing', 'crestfallen', 'woeful'] },
];

export const ANTONYMS = [
  { w: 'brave', tier: 1, s: ['afraid', 'scared', 'timid'], d: ['bold', 'daring', 'sturdy'] },
  { w: 'hot', tier: 1, s: ['cold', 'freezing', 'chilly'], d: ['warm', 'burning', 'mild'] },
  { w: 'fast', tier: 1, s: ['slow', 'sluggish', 'crawling'], d: ['rapid', 'speedy', 'swift'] },
  { w: 'day', tier: 1, s: ['night', 'night-time', 'dusk'], d: ['morning', 'noon', 'sunrise'] },
  { w: 'happy', tier: 2, s: ['sad', 'gloomy', 'miserable'], d: ['cheerful', 'glad', 'buoyant'] },
  { w: 'loud', tier: 2, s: ['quiet', 'silent', 'hushed'], d: ['noisy', 'roaring', 'blaring'] },
  { w: 'open', tier: 2, s: ['shut', 'closed', 'sealed'], d: ['ajar', 'unlocked', 'wide'] },
  { w: 'empty', tier: 3, s: ['full', 'packed', 'filled'], d: ['bare', 'hollow', 'vacant'] },
  { w: 'strong', tier: 3, s: ['weak', 'feeble', 'frail'], d: ['mighty', 'sturdy', 'tough'] },
  { w: 'ancient', tier: 4, s: ['modern', 'new', 'brand-new'], d: ['archaic', 'antique', 'aged'] },
  { w: 'generous', tier: 5, s: ['mean', 'stingy', 'selfish'], d: ['kind', 'giving', 'charitable'] },
  { w: 'innocent', tier: 5, s: ['guilty', 'blameworthy'], d: ['naive', 'pure', 'blameless'] },
  { w: 'arrive', tier: 6, s: ['depart', 'leave', 'set off'], d: ['reach', 'land', 'appear'] },
  { w: 'ancient', tier: 7, s: ['contemporary', 'modern', 'up-to-date'], d: ['aged', 'time-worn', 'archaic'] },
  { w: 'courageous', tier: 8, s: ['cowardly', 'timorous', 'fearful'], d: ['valiant', 'gallant', 'stout'] },
  { w: 'abundant', tier: 9, s: ['scarce', 'sparse', 'meagre'], d: ['plentiful', 'copious', 'rife'] },
  { w: 'transparent', tier: 10, s: ['opaque', 'cloudy', 'murky'], d: ['clear', 'sheer', 'lucent'] },
  { w: 'benevolent', tier: 11, s: ['malevolent', 'spiteful', 'malign'], d: ['kindly', 'benign', 'caring'] },
  { w: 'elastic', tier: 12, s: ['rigid', 'inflexible', 'unbending'], d: ['springy', 'supple', 'stretchy'] },
  { w: 'frugal', tier: 13, s: ['extravagant', 'lavish', 'profligate'], d: ['thrifty', 'sparing', 'economical'] },
  { w: 'verbose', tier: 14, s: ['terse', 'concise', 'laconic'], d: ['wordy', 'rambling', 'lengthy'] },
];

export const ANALOGIES = [
  { a: 'puppy', b: 'dog', c: 'kitten', d: 'cat', tier: 1 },
  { a: 'kitten', b: 'cat', c: 'puppy', d: 'dog', tier: 1 },
  { a: 'small', b: 'tiny', c: 'big', d: 'huge', tier: 2 },
  { a: 'foot', b: 'shoe', c: 'hand', d: 'glove', tier: 2 },
  { a: 'bird', b: 'nest', c: 'bee', d: 'hive', tier: 2 },
  { a: 'cold', b: 'ice', c: 'sun', d: 'desert', tier: 3 },
  { a: 'slow', b: 'snail', c: 'fast', d: 'cheetah', tier: 3 },
  { a: 'petal', b: 'flower', c: 'branch', d: 'tree', tier: 4 },
  { a: 'sword', b: 'knight', c: 'wand', d: 'wizard', tier: 4 },
  { a: 'hungry', b: 'eat', c: 'thirsty', d: 'drink', tier: 4 },
  { a: 'ship', b: 'harbour', c: 'train', d: 'station', tier: 5 },
  { a: 'author', b: 'book', c: 'composer', d: 'symphony', tier: 6 },
  { a: 'scent', b: 'nose', c: 'sound', d: 'ear', tier: 6 },
  { a: 'thermometer', b: 'temperature', c: 'clock', d: 'time', tier: 7 },
  { a: 'drought', b: 'thirst', c: 'feast', d: 'appetite', tier: 8 },
  { a: 'chisel', b: 'sculptor', c: 'needle', d: 'tailor', tier: 8 },
  { a: 'optimist', b: 'hopeful', c: 'pessimist', d: 'doubtful', tier: 9 },
  { a: 'cartographer', b: 'maps', c: 'lexicographer', d: 'dictionaries', tier: 10 },
  { a: 'ephemeral', b: 'mayfly', c: 'enduring', d: 'oak', tier: 11 },
  { a: 'melody', b: 'notes', c: 'mosaic', d: 'tiles', tier: 12 },
];

// odd-one-out: categoria + membro estranho
export const ODD_ONE_OUT = [
  { tier: 1, cat: 'colours', members: ['crimson', 'scarlet', 'emerald', 'ruby'], odd: 'emerald' },
  { tier: 1, cat: 'animals', members: ['otter', 'heron', 'badger', 'sparrow'], odd: 'sparrow' },
  { tier: 1, cat: 'fruit', members: ['plum', 'raspberry', 'carrot', 'pear'], odd: 'carrot' },
  { tier: 2, cat: 'things you wear', members: ['mitten', 'poncho', 'cauldron', 'bonnet'], odd: 'cauldron' },
  { tier: 2, cat: 'weather', members: ['drizzle', 'blizzard', 'hailstone', 'echo'], odd: 'echo' },
  { tier: 3, cat: 'sounds', members: ['clatter', 'rumble', 'shimmer', 'crackle'], odd: 'shimmer' },
  { tier: 3, cat: 'birds of prey', members: ['kestrel', 'sparrow', 'osprey', 'buzzard'], odd: 'sparrow' },
  { tier: 4, cat: 'ships', members: ['galleon', 'tug', 'canoe', 'vigil'], odd: 'vigil' },
  { tier: 5, cat: 'strong feelings', members: ['fury', 'delight', 'terror', 'hush'], odd: 'hush' },
  { tier: 6, cat: 'movements', members: ['saunter', 'trudge', 'loiter', 'murmur'], odd: 'murmur' },
  { tier: 7, cat: 'kinds of houses', members: ['cottage', 'manor', 'hamlet', 'bungalow'], odd: 'hamlet' },
  { tier: 8, cat: 'shining', members: ['gleaming', 'dazzling', 'flickering', 'parched'], odd: 'parched' },
  { tier: 9, cat: 'quick movements', members: ['dart', 'sprint', 'lunge', 'dawdle'], odd: 'dawdle' },
  { tier: 10, cat: 'book parts', members: ['spine', 'chapter', 'index', 'stanza'], odd: 'stanza' },
  { tier: 11, cat: 'being mean', members: ['spiteful', 'callous', 'vindictive', 'lenient'], odd: 'lenient' },
  { tier: 12, cat: 'speaking quietly', members: ['murmur', 'whisper', 'mutter', 'proclaim'], odd: 'proclaim' },
];

// lacuna de contexto: frase com lacuna + resposta + distratores
export const CONTEXT_GAPS = [
  { tier: 1, before: 'The lost puppy felt very ', after: ' until it found its owner.', answer: 'lonely', d: ['cheerful', 'brave'] },
  { tier: 1, before: 'We packed a picnic because the sky was ', after: ' and blue.', answer: 'clear', d: ['stormy', 'crooked'] },
  { tier: 2, before: 'Be careful — the ice is as ', after: ' as glass.', answer: 'slippery', d: ['rough', 'noisy'] },
  { tier: 2, before: 'The dragon was ', after: ' and guarded its treasure fiercely.', answer: 'fierce', d: ['timid', 'sleepy'] },
  { tier: 3, before: 'After the long walk, Tom was ', after: ' and drank the whole jug.', answer: 'thirsty', d: ['restless', 'chatty'] },
  { tier: 3, before: 'The wizard spoke in a ', after: ' voice that echoed round the cave.', answer: 'booming', d: ['whispered', 'cheerful'] },
  { tier: 4, before: 'The treasure was so ', after: ' that it dazzled everyone who looked.', answer: 'gleaming', d: ['tarnished', 'buried'] },
  { tier: 4, before: 'She gave a ', after: ' reply, answering before anyone had finished asking.', answer: 'prompt', d: ['lazy', 'confused'] },
  { tier: 5, before: 'The forest was ', after: ' — not a single leaf stirred.', answer: 'motionless', d: ['rustling', 'crowded'] },
  { tier: 5, before: 'Grandpa told a ', after: ' tale that made us laugh until we cried.', answer: 'hilarious', d: ['grim', 'dull'] },
  { tier: 6, before: 'The clue was so ', after: ' that only the sharpest detective would spot it.', answer: 'subtle', d: ['obvious', 'glaring'] },
  { tier: 6, before: 'He was ', after: ' about winning: he had practised every single day.', answer: 'confident', d: ['doubtful', 'curious'] },
  { tier: 7, before: 'The old house had a ', after: ' atmosphere; even the floorboards seemed to whisper.', answer: 'eerie', d: ['welcoming', 'cosy'] },
  { tier: 7, before: 'Her handwriting was so ', after: ' that the note had to be read twice.', answer: 'illegible', d: ['elegant', 'tidy'] },
  { tier: 8, before: 'The champion remained ', after: ' despite the roaring crowd.', answer: 'composed', d: ['rattled', 'boisterous'] },
  { tier: 8, before: 'The soup smelled so ', after: ' that everyone asked for seconds.', answer: 'tempting', d: ['revolting', 'peculiar'] },
  { tier: 9, before: 'The explorer made a ', after: ' decision, checking every rope twice.', answer: 'prudent', d: ['hasty', 'reckless'] },
  { tier: 10, before: 'The story was ', after: ' — it hinted at secrets it never explained.', answer: 'enigmatic', d: ['frank', 'boring'] },
  { tier: 11, before: 'The king was ', after: ', punishing even the smallest mistake.', answer: 'ruthless', d: ['merciful', 'weary'] },
  { tier: 12, before: 'Her memory of the shipwreck was ', after: ' — clear as the day it happened.', answer: 'vivid', d: ['hazy', 'fleeting'] },
];

// ortografia: palavra correta + erros comuns + pista de significado
export const SPELLINGS = [
  { tier: 1, correct: 'because', wrong: ['becuase', 'becase', 'becuas'], hint: 'for the reason that' },
  { tier: 1, correct: 'friend', wrong: ['freind', 'frend', 'frirend'], hint: 'a person you like and trust' },
  { tier: 2, correct: 'said', wrong: ['sayed', 'sed', 'saide'], hint: 'past tense of “say”' },
  { tier: 2, correct: 'beautiful', wrong: ['beutiful', 'beatiful', 'butiful'], hint: 'very pretty to look at' },
  { tier: 3, correct: 'believe', wrong: ['beleive', 'belive', 'beleve'], hint: 'to think something is true' },
  { tier: 3, correct: 'caught', wrong: ['cought', 'caugth', 'cort'], hint: 'past tense of “catch”' },
  { tier: 4, correct: 'separate', wrong: ['seperate', 'separete', 'sepparate'], hint: 'to set or keep apart' },
  { tier: 4, correct: 'favourite', wrong: ['favorite', 'faverite', 'favorit'], hint: 'the one you like best (British spelling)' },
  { tier: 5, correct: 'necessary', wrong: ['neccessary', 'necesary', 'necissary'], hint: 'needed; required' },
  { tier: 5, correct: 'surprise', wrong: ['suprise', 'surprize', 'sruprise'], hint: 'something unexpected' },
  { tier: 6, correct: 'definitely', wrong: ['definately', 'definitly', 'defenetly'], hint: 'without any doubt' },
  { tier: 6, correct: 'rhythm', wrong: ['rythm', 'rhythem', 'rythum'], hint: 'a repeated beat in music' },
  { tier: 7, correct: 'occasion', wrong: ['occassion', 'ocassion', 'occacion'], hint: 'a special event or time' },
  { tier: 7, correct: 'government', wrong: ['goverment', 'governement', 'govornment'], hint: 'the group that runs a country' },
  { tier: 8, correct: 'mischievous', wrong: ['mischievious', 'mischevious', 'mischivous'], hint: 'playfully naughty' },
  { tier: 8, correct: 'conscience', wrong: ['concience', 'conscence', 'consience'], hint: 'your inner sense of right and wrong' },
  { tier: 9, correct: 'existence', wrong: ['existance', 'exsistance', 'existense'], hint: 'the state of being alive or real' },
  { tier: 10, correct: 'argument', wrong: ['arguement', 'arguament', 'argumant'], hint: 'a disagreement, or a reason supporting a view' },
  { tier: 11, correct: 'questionnaire', wrong: ['questionaire', 'questionnnaire', 'questionairre'], hint: 'a form with a list of questions' },
  { tier: 12, correct: 'bureaucracy', wrong: ['beaurocracy', 'bureaucracyy', 'burocracy'], hint: 'a system of officials and rules' },
];
