// Sucata: T13 a T18.
//
// Estas seis são as que mais pedem cuidado com duas coisas da spec: material
// pesado ou cortante (ajuda de adulto) e peças pequenas (aviso de segurança).
// O aviso entra no texto do passo em que o perigo aparece, não num banner
// solto — a criança lê "pegue a tesoura com um adulto" na hora em que vai
// pegar a tesoura.
//
// O `objectBox` é estimativa a olho; a arte final mede a caixa por pixel.

export default [
  {
    id: 't13',
    slug: 'toilet-roll-owl',
    category: 'recycled',
    difficulty: 1,
    estimatedMinutes: 20,
    requiresPrinting: false,
    // Cada quadro parte do anterior e acrescenta só uma peça via edição mascarada.
    baseImage: 'assets/tutorials/toilet-roll-owl/base.webp',
    framePattern: 'assets/tutorials/toilet-roll-owl/step-%s.webp',
    materials: ['material.tube', 'material.paper', 'material.glue', 'material.marker'],
    steps: [
      { veil: 'none', image: '01-dobra' },
      { veil: 'none', image: '02-forro' },
      { veil: 'none', image: '03-olhos' },
      { veil: 'none', image: '04-bico' },
      { veil: 'none', image: '05-asas' },
      { veil: 'none', image: '06-penas' },
      { veil: 'none', image: '07-nome' },
    ],
    copy: {
      pt: {
        title: 'Coruja de Rolinho',
        description: 'Um rolo de papel higiênico vira uma coruja com orelhas, olhos e asas.',
        steps: [
          { instruction: 'Dobre as duas bordas de cima do rolinho para dentro, formando as orelhas.', tip: 'Aperte cada lado para criar duas pontinhas.' },
          { instruction: 'Encape o corpo do rolinho com papel colorido.', tip: 'Alise o papel e deixe as orelhas sem cobrir.' },
          { instruction: 'Cole dois olhos grandes de papel na parte de cima.', tip: 'Ponha-os lado a lado, deixando espaço no meio para o bico.' },
          { instruction: 'Cole um bico pequeno entre os olhos.', tip: 'Um triângulo de papel laranja já funciona.' },
          { instruction: 'Cole uma asa de papel em cada lado do corpo.', tip: 'Cole só a ponta de cima para as asas ficarem abertas.' },
          { instruction: 'Desenhe pontinhos e risquinhos para fazer as penas.', tip: 'Repita poucos traços como um padrão.' },
          { instruction: 'Escreva um nome numa etiqueta e coloque-a ao lado da coruja.', tip: 'Escolha um nome que combine com a personalidade dela.' },
        ],
      },
      en: {
        title: 'Toilet Roll Owl',
        description: 'A cardboard tube turns into an owl with ears, eyes and wings.',
        steps: [
          { instruction: 'Fold the two top edges of the tube inward to make the ears.', tip: 'Press each side to form two little points.' },
          { instruction: 'Cover the tube body with coloured paper.', tip: 'Smooth the paper down and leave the folded ears uncovered.' },
          { instruction: 'Glue two big paper eyes near the top.', tip: 'Place them side by side, leaving room for the beak between them.' },
          { instruction: 'Glue a small beak between the eyes.', tip: 'A little orange paper triangle works well.' },
          { instruction: 'Glue one paper wing to each side of the body.', tip: 'Glue only the top edge so the wings can stick out.' },
          { instruction: 'Draw little dots and dashes to make feathers.', tip: 'Repeat a few marks to create a pattern.' },
          { instruction: 'Write a name on a small tag and place it beside the owl.', tip: 'Choose a name that matches its personality.' },
        ],
      },
      es: {
        title: 'Búho del Tubo',
        description: 'Un tubo de cartón se convierte en un búho con orejas, ojos y alas.',
        steps: [
          { instruction: 'Dobla los dos bordes de arriba del tubo hacia dentro para formar las orejas.', tip: 'Aprieta cada lado para crear dos puntitas.' },
          { instruction: 'Forra el cuerpo del tubo con papel de colores.', tip: 'Alisa el papel y deja las orejas sin cubrir.' },
          { instruction: 'Pega dos ojos grandes de papel en la parte de arriba.', tip: 'Ponlos lado a lado y deja sitio para el pico en medio.' },
          { instruction: 'Pega un pico pequeño entre los ojos.', tip: 'Un triángulo pequeño de papel naranja funciona bien.' },
          { instruction: 'Pega un ala de papel a cada lado del cuerpo.', tip: 'Pega solo el borde de arriba para que las alas sobresalgan.' },
          { instruction: 'Dibuja puntitos y rayitas para hacer las plumas.', tip: 'Repite unas pocas marcas para crear un patrón.' },
          { instruction: 'Escribe un nombre en una etiqueta pequeña y ponla junto al búho.', tip: 'Elige un nombre que vaya con su personalidad.' },
        ],
      },
    },
  },
  {
    id: 't14',
    slug: 'cardboard-robot',
    category: 'recycled',
    difficulty: 2,
    estimatedMinutes: 40,
    requiresPrinting: false,
    // Os quadros são estágios do mesmo robô, não sete gerações independentes.
    // Cada passo acrescenta uma peça; fora da máscara da peça, a foto-base fica
    // idêntica. A ordem segue T14 da spec e a rotina está em docs/LESSONS.md.
    baseImage: 'assets/tutorials/cardboard-robot/base.webp',
    framePattern: 'assets/tutorials/cardboard-robot/step-%s.webp',
    materials: [
      'material.box', 'material.cardboard', 'material.tube', 'material.paper',
      'material.tape', 'material.glue', 'material.marker', 'material.scissors',
    ],
    steps: [
      { veil: 'none', image: '01-corpo' },
      { veil: 'none', image: '02-cabeca' },
      { veil: 'none', image: '03-bracos' },
      { veil: 'none', image: '04-pes' },
      { veil: 'none', image: '05-botoes' },
      { veil: 'none', image: '06-olhos-antenas' },
      { veil: 'none', image: '07-nome-trabalho' },
    ],
    copy: {
      pt: {
        title: 'Robô de Papelão',
        description: 'Caixas e rolinhos viram um robô com botões e olhos.',
        steps: [
          { instruction: 'Escolha uma caixa para o corpo.', tip: 'Caixa de sapato fica baixa e firme; caixa de cereal fica alta.' },
          { instruction: 'Coloque uma caixa menor em cima para fazer a cabeça.', tip: 'Centralize-a e prenda com fita ou cola.' },
          { instruction: 'Faça dois braços com tubos de papelão.', tip: 'Use rolinhos ou enrole papel. Peça ajuda a um adulto para cortar papelão grosso.' },
          { instruction: 'Prenda dois pezinhos de papelão na base.', tip: 'Uma caixinha em cada lado ajuda o robô a ficar em pé.' },
          { instruction: 'Escolha e prenda os botões do robô.', tip: 'Use botões, tampinhas ou círculos de papel; organize as cores antes de colar.' },
          { instruction: 'Desenhe os olhos e acrescente as antenas.', tip: 'Dois olhos grandes e antenas de papel dão personalidade.' },
          { instruction: 'Dê um trabalho e um nome ao seu robô.', tip: 'Escreva na etiqueta e conte o que ele faz.' },
        ],
      },
      en: {
        title: 'Cardboard Robot',
        description: 'Boxes and tubes turn into a robot with buttons and eyes.',
        steps: [
          { instruction: 'Choose a box for the body.', tip: 'A shoebox is short and steady; a cereal box is tall.' },
          { instruction: 'Place a smaller box on top for the head.', tip: 'Center it and secure it with tape or glue.' },
          { instruction: 'Make two arms from cardboard tubes.', tip: 'Use cardboard rolls or roll paper. Ask an adult to cut thick cardboard.' },
          { instruction: 'Attach two small cardboard feet at the bottom.', tip: 'A small box on each side helps the robot stand.' },
          { instruction: 'Choose and attach the robot’s buttons.', tip: 'Use buttons, bottle caps, or paper circles; plan the colours before gluing.' },
          { instruction: 'Draw the eyes and add antennae.', tip: 'Two big eyes and paper antennae give the robot a personality.' },
          { instruction: 'Give your robot a job and a name.', tip: 'Write it on the tag and tell what the robot does.' },
        ],
      },
      es: {
        title: 'Robot de Cartón',
        description: 'Cajas y tubos se convierten en un robot con botones y ojos.',
        steps: [
          { instruction: 'Elige una caja para el cuerpo.', tip: 'Una caja de zapatos queda baja y firme; una de cereales es alta.' },
          { instruction: 'Coloca una caja más pequeña encima para hacer la cabeza.', tip: 'Céntrala y sujétala con cinta o pegamento.' },
          { instruction: 'Haz dos brazos con tubos de cartón.', tip: 'Usa tubos o enrolla papel. Pide ayuda a un adulto para cortar cartón grueso.' },
          { instruction: 'Pega dos pies pequeños de cartón en la base.', tip: 'Una cajita a cada lado ayuda a que el robot se mantenga de pie.' },
          { instruction: 'Elige y pega los botones del robot.', tip: 'Usa botones, tapas o círculos de papel; ordena los colores antes de pegarlos.' },
          { instruction: 'Dibuja los ojos y añade antenas.', tip: 'Dos ojos grandes y antenas de papel le dan personalidad.' },
          { instruction: 'Dale un trabajo y un nombre a tu robot.', tip: 'Escríbelo en la etiqueta y cuenta qué hace el robot.' },
        ],
      },
    },
  },
  {
    id: 't15',
    slug: 'egg-carton-flower-garden',
    category: 'recycled',
    difficulty: 1,
    estimatedMinutes: 30,
    requiresPrinting: false,
    baseImage: 'assets/tutorials/egg-carton-flower-garden/base.webp',
    framePattern: 'assets/tutorials/egg-carton-flower-garden/step-%s.webp',
    materials: [
      'material.eggCarton', 'material.paint', 'material.glue', 'material.card',
      'material.paper', 'material.pipeCleaner', 'material.scissors', 'material.marker',
    ],
    steps: [
      { veil: 'none', image: '01-cortar' },
      { veil: 'none', image: '02-petalas' },
      { veil: 'none', image: '03-pintar' },
      { veil: 'none', image: '04-caules' },
      { veil: 'none', image: '05-flores' },
      { veil: 'none', image: '06-folhas' },
      { veil: 'none', image: '07-insetos' },
    ],
    copy: {
      pt: {
        title: 'Jardim de Flores',
        description: 'Uma embalagem de ovos vira uma floreira de papelão com flores, folhas e abelhas de papel.',
        steps: [
          { instruction: 'Separe os copinhos da embalagem com ajuda de um adulto.', tip: 'Conte os copinhos para escolher quantas flores vai fazer.', safety: 'Peça ajuda de um adulto para cortar o papelão; apoie-o na mesa.' },
          { instruction: 'Faça quatro cortes pequenos em cada copinho para formar pétalas.', tip: 'Deixe a base do copinho inteira para ele continuar firme.', safety: 'A tesoura fica com o adulto.' },
          { instruction: 'Pinte os copinhos e a base de papelão; espere secar.', tip: 'Use uma cor por flor e pinte a base antes de montar.' },
          { instruction: 'Encaixe caules verdes nos copinhos que ficaram presos à base.', tip: 'Deixe espaço entre os caules para cada flor aparecer.' },
          { instruction: 'Cole uma flor na ponta de cada caule.', tip: 'Segure cada flor um instante para a cola firmar.' },
          { instruction: 'Cole folhas de papel ao redor dos caules.', tip: 'Uma folha comprida em cada caule já parece um jardim.' },
          { instruction: 'Desenhe e cole abelhinhas de papel perto das flores.', tip: 'Faça cada abelhinha pequena para ela não esconder as flores.' },
        ],
      },
      en: {
        title: 'Egg Carton Flower Garden',
        description: 'An egg carton becomes a cardboard flower garden with paper flowers, leaves and bees.',
        steps: [
          { instruction: 'Separate the cups from the carton with an adult.', tip: 'Count the cups to decide how many flowers to make.', safety: 'Ask an adult to cut the carton, with it resting on the table.' },
          { instruction: 'Make four short cuts in each cup to form petals.', tip: 'Leave the bottom of each cup intact so it stays sturdy.', safety: 'An adult should handle the scissors.' },
          { instruction: 'Paint the cups and cardboard base; let them dry.', tip: 'Use one colour per flower and paint the base before assembly.' },
          { instruction: 'Set green stems into the cups that remain attached to the base.', tip: 'Leave space between stems so each flower can show.' },
          { instruction: 'Glue one flower cup to the end of each stem.', tip: 'Hold each flower for a moment while the glue sets.' },
          { instruction: 'Glue paper leaves around the stems.', tip: 'One long leaf on each stem already looks like a garden.' },
          { instruction: 'Draw and glue small paper bees near the flowers.', tip: 'Keep each bee small so it does not hide the flowers.' },
        ],
      },
      es: {
        title: 'Jardín de Flores',
        description: 'Una huevera se convierte en un jardín de cartón con flores, hojas y abejas de papel.',
        steps: [
          { instruction: 'Separa los vasitos del cartón con ayuda de un adulto.', tip: 'Cuenta los vasitos para decidir cuántas flores harás.', safety: 'Pide a un adulto que corte el cartón, apoyado sobre la mesa.' },
          { instruction: 'Haz cuatro cortes pequeños en cada vasito para formar pétalos.', tip: 'Deja intacta la base del vasito para que siga firme.', safety: 'Las tijeras las usa un adulto.' },
          { instruction: 'Pinta los vasitos y la base de cartón; deja que se sequen.', tip: 'Usa un color por flor y pinta la base antes de montarla.' },
          { instruction: 'Coloca tallos verdes en los vasitos que siguen unidos a la base.', tip: 'Deja espacio entre los tallos para que se vea cada flor.' },
          { instruction: 'Pega una flor en la punta de cada tallo.', tip: 'Sujeta cada flor un momento para que se fije el pegamento.' },
          { instruction: 'Pega hojas de papel alrededor de los tallos.', tip: 'Una hoja larga en cada tallo ya parece un jardín.' },
          { instruction: 'Dibuja y pega abejitas de papel cerca de las flores.', tip: 'Haz cada abejita pequeña para que no tape las flores.' },
        ],
      },
    },
  },
  {
    id: 't16',
    slug: 'cereal-box-desk-organiser',
    category: 'recycled',
    difficulty: 2,
    estimatedMinutes: 35,
    requiresPrinting: false,
    baseImage: 'assets/tutorials/cereal-box-desk-organiser/base.webp',
    framePattern: 'assets/tutorials/cereal-box-desk-organiser/step-%s.webp',
    materials: [
      'material.cerealBox', 'material.paper', 'material.tape', 'material.marker',
      'material.scissors', 'material.cardboard', 'material.glue',
    ],
    steps: [
      { veil: 'none', image: '01-marcar' },
      { veil: 'none', image: '02-cortar' },
      { veil: 'none', image: '03-forrar' },
      { veil: 'none', image: '04-etiqueta' },
      { veil: 'none', image: '05-decorar' },
      { veil: 'none', image: '06-divisoria' },
      { veil: 'none', image: '07-lapices' },
    ],
    copy: {
      pt: {
        title: 'Organizador de Mesa',
        description: 'Uma caixa de cereal vira um organizador para lápis, pincel e tesoura.',
        steps: [
          { instruction: 'Marque com caneta a altura do organizador na caixa.', tip: 'Conte quantos lápis quer guardar; a caixa precisa ser mais alta que eles.' },
          { instruction: 'Com um adulto, corte a caixa nessa marca.', tip: 'Vire a lâmina para longe do corpo enquanto corta.', safety: 'Cortar papelão grosso pede ajuda de um adulto.' },
          { instruction: 'Cubra o lado de fora com papel colorido.', tip: 'Alise o papel e deixe a parte de dentro sem cobrir.' },
          { instruction: 'Cole uma etiqueta clara na frente para escrever o nome.', tip: 'Um retângulo de papel claro fica fácil de ler.' },
          { instruction: 'Decore com desenhos e listras.', tip: 'Use cores diferentes para cada lado do organizador.' },
          { instruction: 'Cole uma divisória de papelão no meio.', tip: 'Dobre uma tira e cole a base no fundo da caixa.' },
          { instruction: 'Encha os compartimentos com lápis, pincel e tesoura.', tip: 'Ponha as coisas mais altas atrás para encontrar tudo.' },
        ],
      },
      en: {
        title: 'Desk Organiser',
        description: 'A cereal box turns into an organiser for pencils, brushes and scissors.',
        steps: [
          { instruction: 'Mark the organiser height on the box with a marker.', tip: 'Count the pencils you want to store; the box must be taller than they are.' },
          { instruction: 'With an adult, cut the box at that mark.', tip: 'Keep the blade pointing away from your body as you cut.', safety: 'Cutting thick cardboard needs an adult.' },
          { instruction: 'Cover the outside with coloured paper.', tip: 'Smooth the paper down and leave the inside bare.' },
          { instruction: 'Glue a pale name label on the front.', tip: 'A light rectangle is easy to read.' },
          { instruction: 'Decorate with drawings and stripes.', tip: 'Use different colours on each side of the organiser.' },
          { instruction: 'Glue a cardboard divider in the middle.', tip: 'Fold a strip and glue its base to the bottom of the box.' },
          { instruction: 'Fill the compartments with pencils, a brush and scissors.', tip: 'Put the tallest things at the back so everything is easy to find.' },
        ],
      },
      es: {
        title: 'Organizador de Mesa',
        description: 'Una caja de cereales se convierte en un organizador para lápices, pinceles y tijeras.',
        steps: [
          { instruction: 'Marca con rotulador la altura del organizador en la caja.', tip: 'Cuenta los lápices que quieres guardar; la caja debe ser más alta que ellos.' },
          { instruction: 'Con un adulto, corta la caja por esa marca.', tip: 'Mantén la hoja apuntando lejos del cuerpo mientras cortas.', safety: 'Cortar cartón grueso requiere ayuda de un adulto.' },
          { instruction: 'Forra el exterior con papel de colores.', tip: 'Alisa el papel y deja el interior sin cubrir.' },
          { instruction: 'Pega delante una etiqueta clara para el nombre.', tip: 'Un rectángulo claro se lee fácilmente.' },
          { instruction: 'Decora con dibujos y rayas.', tip: 'Usa colores distintos en cada lado del organizador.' },
          { instruction: 'Pega un separador de cartón en el medio.', tip: 'Dobla una tira y pega la base al fondo de la caja.' },
          { instruction: 'Llena los compartimentos con lápices, un pincel y tijeras.', tip: 'Pon lo más alto atrás para encontrar todo fácilmente.' },
        ],
      },
    },
  },
  {
    id: 't17',
    slug: 'bottle-cap-mosaic',
    category: 'recycled',
    difficulty: 2,
    estimatedMinutes: 30,
    requiresPrinting: false,
    baseImage: 'assets/tutorials/bottle-cap-mosaic/base.webp',
    framePattern: 'assets/tutorials/bottle-cap-mosaic/step-%s.webp',
    materials: ['material.caps', 'material.card', 'material.paper', 'material.glue', 'material.marker'],
    steps: [
      { veil: 'none', image: '01-coracao' },
      { veil: 'none', image: '02-cores' },
      { veil: 'none', image: '03-testar' },
      { veil: 'none', image: '04-ajustar' },
      { veil: 'none', image: '05-colar-centro' },
      { veil: 'none', image: '06-borda' },
      { veil: 'none', image: '07-finalizar' },
    ],
    copy: {
      pt: {
        title: 'Mosaico de Tampinhas',
        description: 'Tampinhas coloridas formam a borda de um coração e deixam espaço para uma mensagem no meio.',
        steps: [
          { instruction: 'Desenhe um coração grande no papelão e deixe o meio livre.', tip: 'O espaço central pode receber sua própria mensagem.' },
          { instruction: 'Separe as tampinhas por cor.', tip: 'Três ou quatro cores já fazem um arco-íris.' },
          { instruction: 'Disponha tampinhas numa metade do coração, sem cola.', tip: 'Apoie-as juntas e siga o contorno do coração.' },
          { instruction: 'Ajuste as cores e deixe o centro livre.', tip: 'Troque as tampinhas agora, antes da cola.' },
          { instruction: 'Cole primeiro as tampinhas do meio da borda.', tip: 'Começar no meio ajuda a manter o coração simétrico.' },
          { instruction: 'Preencha a outra metade sem cobrir o centro.', tip: 'Deixe espaço para a mensagem aparecer.' },
          { instruction: 'Reforce o contorno do coração e deixe o centro livre para sua mensagem.', tip: 'Escreva a mensagem depois que a cola secar.' },
        ],
      },
      en: {
        title: 'Bottle Cap Mosaic',
        description: 'Colourful caps make a heart-shaped border, leaving room for a message in the middle.',
        steps: [
          { instruction: 'Draw a big heart on the card and leave the middle open.', tip: 'The blank centre can hold your own message.' },
          { instruction: 'Sort the caps by colour.', tip: 'Three or four colours already make a rainbow.' },
          { instruction: 'Arrange caps along one half of the heart without glue.', tip: 'Keep them close together and follow the outline.' },
          { instruction: 'Adjust the colours and keep the centre open.', tip: 'Swap caps around now, before adding glue.' },
          { instruction: 'Glue the middle caps along the border first.', tip: 'Starting in the middle helps keep the heart balanced.' },
          { instruction: 'Fill the other half without covering the centre.', tip: 'Leave room for the message to show.' },
          { instruction: 'Reinforce the heart outline and leave the centre open for your message.', tip: 'Write the message after the glue dries.' },
        ],
      },
      es: {
        title: 'Mosaico de Tapones',
        description: 'Tapones de colores forman un borde de corazón y dejan sitio para un mensaje en el centro.',
        steps: [
          { instruction: 'Dibuja un corazón grande en el cartón y deja libre el centro.', tip: 'El espacio vacío puede llevar tu propio mensaje.' },
          { instruction: 'Separa los tapones por color.', tip: 'Tres o cuatro colores ya forman un arcoíris.' },
          { instruction: 'Coloca tapones en una mitad del corazón, sin pegamento.', tip: 'Ponlos juntos y sigue el contorno.' },
          { instruction: 'Ajusta los colores y deja libre el centro.', tip: 'Cambia los tapones ahora, antes de poner pegamento.' },
          { instruction: 'Pega primero los tapones del medio del borde.', tip: 'Empezar por el centro ayuda a mantener el corazón equilibrado.' },
          { instruction: 'Rellena la otra mitad sin tapar el centro.', tip: 'Deja sitio para que se vea el mensaje.' },
          { instruction: 'Repasa el contorno del corazón y deja el centro libre para tu mensaje.', tip: 'Escribe el mensaje cuando se seque el pegamento.' },
        ],
      },
    },
  },
  {
    id: 't18',
    slug: 'cardboard-marble-maze',
    category: 'recycled',
    difficulty: 3,
    estimatedMinutes: 45,
    requiresPrinting: false,
    baseImage: 'assets/tutorials/cardboard-marble-maze/base.webp',
    framePattern: 'assets/tutorials/cardboard-marble-maze/step-%s.webp',
    materials: [
      'material.box', 'material.cardboard', 'material.glue', 'material.marker',
      'material.scissors', 'material.marble',
    ],
    steps: [
      { veil: 'none', image: '01-ruta' },
      { veil: 'none', image: '02-inicio-meta' },
      { veil: 'none', image: '03-tiras' },
      { veil: 'none', image: '04-paredes' },
      { veil: 'none', image: '05-callejones' },
      { veil: 'none', image: '06-prueba' },
      { veil: 'none', image: '07-juego' },
    ],
    copy: {
      pt: {
        title: 'Labirinto de Papelão',
        description: 'Tiras de papelão coladas numa tampa de caixa viram um labirinto para a bolinha.',
        steps: [
          { instruction: 'Desenhe um caminho de labirinto na tampa da caixa.', tip: 'Um caminho só é mais fácil de acertar; os becos sem saída entram depois.' },
          { instruction: 'Marque o início e o fim nos pontos de entrada e saída do caminho.', tip: 'Ligue um X e um círculo ao caminho, sem criar atalhos.' },
          { instruction: 'Com um adulto, corte tiras de papelão para as paredes.', tip: 'Faça tiras da altura de dois dedos.', safety: 'Cortar papelão grosso pede ajuda de um adulto.' },
          { instruction: 'Cole as paredes sobre o caminho desenhado.', tip: 'Cole primeiro as curvas e depois as partes retas.' },
          { instruction: 'Acrescente dois becos sem saída.', tip: 'Eles deixam o percurso mais divertido.' },
          { instruction: 'Teste a bolinha e ajuste as paredes.', tip: 'Se a bolinha ficar presa, afaste um pouco a parede.' },
          { instruction: 'Brinque e cronometre quem chega primeiro.', tip: 'Tente melhorar seu tempo a cada rodada.', safety: 'A bolinha é uma peça pequena; mantenha-a longe de crianças pequenas.' },
        ],
      },
      en: {
        title: 'Cardboard Marble Maze',
        description: 'Cardboard strips glued into a box lid make a maze for a small ball.',
        steps: [
          { instruction: 'Draw a maze route on the box lid.', tip: 'One route is easiest to build; the dead ends come later.' },
          { instruction: 'Mark the start and finish at the route’s entrance and exit.', tip: 'Connect one X and one circle to the route without making shortcuts.' },
          { instruction: 'With an adult, cut cardboard strips for the walls.', tip: 'Make the strips about two fingers tall.', safety: 'Cutting thick cardboard needs an adult.' },
          { instruction: 'Glue the walls over the drawn route.', tip: 'Glue the curves first, then the straight sections.' },
          { instruction: 'Add two dead ends.', tip: 'Dead ends make the route more fun.' },
          { instruction: 'Test the ball and adjust the walls.', tip: 'If the ball gets stuck, move a wall out a little.' },
          { instruction: 'Play and time who reaches the finish first.', tip: 'Try to beat your time on the next round.', safety: 'The ball is a small part; keep it away from little children.' },
        ],
      },
      es: {
        title: 'Laberinto de Cartón',
        description: 'Tiras de cartón pegadas en una tapa de caja forman un laberinto para una bolita.',
        steps: [
          { instruction: 'Dibuja un camino de laberinto en la tapa de la caja.', tip: 'Un solo camino es el más fácil; los callejones sin salida se añaden después.' },
          { instruction: 'Marca el inicio y el final en la entrada y salida del camino.', tip: 'Conecta una X y un círculo al recorrido sin crear atajos.' },
          { instruction: 'Con un adulto, corta tiras de cartón para las paredes.', tip: 'Haz las tiras de unos dos dedos de alto.', safety: 'Cortar cartón grueso requiere ayuda de un adulto.' },
          { instruction: 'Pega las paredes sobre el camino dibujado.', tip: 'Pega primero las curvas y luego los tramos rectos.' },
          { instruction: 'Añade dos callejones sin salida.', tip: 'Los callejones hacen más divertido el recorrido.' },
          { instruction: 'Prueba la bolita y ajusta las paredes.', tip: 'Si la bolita se atasca, separa un poco la pared.' },
          { instruction: 'Juega y cronometra quién llega primero.', tip: 'Intenta mejorar tu tiempo en la siguiente vuelta.', safety: 'La bolita es una pieza pequeña; mantenla lejos de niños pequeños.' },
        ],
      },
    },
  },
];
