// Sucata: T13 a T18.
//
// Estas seis são as que mais pedem cuidado com duas coisas da spec: material
// pesado ou cortante (ajuda de adulto) e peças pequenas (aviso de segurança).
// O aviso entra no texto do passo em que o perigo aparece, não num banner
// solto — a criança lê "pegue a tesoura com um adulto" na hora em que vai
// pegar a tesoura.
//
// O `objectBox` é estimativa a olho; a arte final mede a caixa por pixel.

export default [
  {
    id: 't13',
    slug: 'toilet-roll-owl',
    category: 'recycled',
    difficulty: 1,
    estimatedMinutes: 20,
    requiresPrinting: false,
    baseImage: 'assets/tutorials/toilet-roll-owl/base.webp',
    objectBox: { x: 0.24, y: 0.12, w: 0.52, h: 0.76 },
    materials: ['material.tube', 'material.paper', 'material.glue', 'material.marker'],
    steps: [
      { veil: 'full' },
      { veil: 'active', region: 'all' },
      { veil: 'active', region: 'top' },
      { veil: 'active', region: 'centre' },
      { veil: 'active', region: 'left' },
      { veil: 'active', region: 'all' },
      { veil: 'none' },
    ],
    copy: {
      pt: {
        title: 'Coruja de Rolinho',
        description: 'Um rolo de papel higiênico vira uma coruja com orelhas, olhos e asas.',
        steps: [
          { instruction: 'Dobre as duas abas do topo para dentro, para fazer as orelhas.', tip: 'As abas viram as orelhas e a marca da dobra fica exatamente no meio.' },
          { instruction: 'Forre o rolo com papel ou pinte ele inteiro.', tip: 'Papel colorido rende mais: o rolo fica só com as bordas aparecendo.' },
          { instruction: 'Cole dois olhos grandes de papel.', tip: 'Círculos grandes deixam a coruja com cara de boba, e coruja boba é a melhor.' },
          { instruction: 'Cole um biquinho pequeno no meio, embaixo dos olhos.', tip: 'Um triângulo pequeno em laranja já parece um bico.' },
          { instruction: 'Prenda duas asas de papel dos lados.', tip: 'Se as asas ficarem soltas, uma gota de cola na base resolve.' },
          { instruction: 'Pense em penas: pontinhos e rabiscos na frente.', tip: 'Repita o mesmo rabisco em vários lugares, como um padrão.' },
          { instruction: 'Dê um nome à sua coruja.', tip: 'Nomeie com um adjetivo: coruja preguiçosa, coruja Guardiã.' },
        ],
      },
      en: {
        title: 'Toilet Roll Owl',
        description: 'A cardboard tube turns into an owl with ears, eyes and wings.',
        steps: [
          { instruction: 'Fold the two top edges inward to make the ears.', tip: 'The flaps become the ears and the fold line lands right in the middle.' },
          { instruction: 'Wrap the tube in paper or colour it in.', tip: 'Coloured paper goes further: only the edges of the tube stay showing.' },
          { instruction: 'Glue on two big paper eyes.', tip: 'Big circles give the owl a silly face, and a silly owl is the best kind.' },
          { instruction: 'Glue a small beak in the middle, under the eyes.', tip: 'A tiny orange triangle already looks like a beak.' },
          { instruction: 'Attach two paper wings to the sides.', tip: 'If the wings keep falling off, one drop of glue on the base does it.' },
          { instruction: 'Think feathers: little dots and scribbles on the front.', tip: 'Repeat the same scribble in several places, like a pattern.' },
          { instruction: 'Give your owl a name.', tip: 'Name it with an adjective: sleepy owl, guard owl.' },
        ],
      },
      es: {
        title: 'Búho del Tubo',
        description: 'Un tubo de cartón se convierte en un búho con orejas, ojos y alas.',
        steps: [
          { instruction: 'Dobla las dos pestañas de arriba hacia dentro para hacer las orejas.', tip: 'Las pestañas hacen de orejas y el pliegue queda justo en el centro.' },
          { instruction: 'Forra el tubo con papel o píntalo entero.', tip: 'El papel de color rinde más: del tubo solo se ven los bordes.' },
          { instruction: 'Pega dos ojos grandes de papel.', tip: 'Los círculos grandes le dan una cara de boba, y un búho boba es el mejor.' },
          { instruction: 'Pega un pico pequeño en el centro, debajo de los ojos.', tip: 'Un triángulo pequeño en naranja ya parece un pico.' },
          { instruction: 'Coloca dos alas de papel a los lados.', tip: 'Si las alas se sueltan, una gota de pegamento en la base las arregla.' },
          { instruction: 'Piensa en plumas: puntitos y rayitas delante.', tip: 'Repite el mismo rayado en varios sitios, como un patrón.' },
          { instruction: 'Ponle nombre a tu búho.', tip: 'Ponle un adjetivo: búho dormilón, búho guardián.' },
        ],
      },
    },
  },
  {
    id: 't14',
    slug: 'cardboard-robot',
    category: 'recycled',
    difficulty: 2,
    estimatedMinutes: 40,
    requiresPrinting: false,
    baseImage: 'assets/tutorials/cardboard-robot/base.webp',
    objectBox: { x: 0.20, y: 0.08, w: 0.60, h: 0.84 },
    materials: ['material.box', 'material.cardboard', 'material.tape', 'material.glue', 'material.marker'],
    steps: [
      { veil: 'full' },
      { veil: 'active', region: 'top' },
      { veil: 'active', region: 'all' },
      { veil: 'active', region: 'bottom' },
      { veil: 'active', region: 'centre' },
      { veil: 'active', region: 'top' },
      { veil: 'none' },
    ],
    copy: {
      pt: {
        title: 'Robô de Papelão',
        description: 'Caixotes e rolinhos viram um robô com botões, olhos e antena.',
        steps: [
          { instruction: 'Escolha um caixote para ser o corpo.', tip: 'Um caixote de sapato fica baixo e firme. Um de cereal fica comprido.' },
          { instruction: 'Prenda uma caixa menor em cima, para a cabeça.', tip: 'Fita em cruz na junta deixa a cabeça firme sem cola.' },
          { instruction: 'Faça os braços com rolinhos de papelão.', tip: 'Enrole a fita no rolinho e o braço para de desenrolar.' },
          { instruction: 'Acrescente as pernas e os pés.', tip: 'Duas caixas viradas para baixo fazem pés que aguentam o robô em pé.' },
          { instruction: 'Desenhe os botões do robô no peito.', tip: 'Círculos de cores diferentes viram botões de tamanhos diferentes.' },
          { instruction: 'Acrescente os olhos e a antena.', tip: 'A antena pode ser um rolinho com uma bola de papel na ponta.' },
          { instruction: 'Dê um trabalho e um nome ao seu robô.', tip: 'Ele limpa a casa? Cuida de plantas? Falar dele como pessoa deixa o robô com cara de personagem.' },
        ],
      },
      en: {
        title: 'Cardboard Robot',
        description: 'Boxes and tubes turn into a robot with buttons, eyes and an antenna.',
        steps: [
          { instruction: 'Pick a box to be the body.', tip: 'A shoebox sits low and steady. A cereal box is long and thin.' },
          { instruction: 'Glue a smaller box on top for the head.', tip: 'Tape in a cross on the joint keeps the head steady without glue.' },
          { instruction: 'Make the arms from cardboard tubes.', tip: 'Wind tape around the tube and the arm stops unrolling.' },
          { instruction: 'Add the legs and the feet.', tip: 'Two boxes upside down make feet that hold the robot standing up.' },
          { instruction: 'Draw the robot buttons on the chest.', tip: 'Circles in different colours make buttons of different sizes.' },
          { instruction: 'Add the eyes and the antenna.', tip: 'The antenna can be a tube with a ball of paper on the end.' },
          { instruction: 'Give your robot a job and a name.', tip: 'Does it clean the house? Look after plants? Talking about it like a person is what makes it a character.' },
        ],
      },
      es: {
        title: 'Robot de Cartón',
        description: 'Cajas y tubos se convierten en un robot con botones, ojos y antena.',
        steps: [
          { instruction: 'Elige una caja para que sea el cuerpo.', tip: 'Una caja de zapatos queda baja y firme. Una de cereales queda larga.' },
          { instruction: 'Pega una caja más pequeña arriba, para la cabeza.', tip: 'Cinta en cruz en la unión asegura la cabeza sin pegamento.' },
          { instruction: 'Haz los brazos con tubos de cartón.', tip: 'Enrolla cinta en el tubo y el brazo deja de desenrollarse.' },
          { instruction: 'Añade las piernas y los pies.', tip: 'Dos cajas boca abajo hacen pies que sostienen al robot de pie.' },
          { instruction: 'Dibuja los botones del robot en el pecho.', tip: 'Círculos de distintos colores hacen botones de distintos tamaños.' },
          { instruction: 'Añade los ojos y la antena.', tip: 'La antena puede ser un tubo con una bola de papel en la punta.' },
          { instruction: 'Dale un oficio y un nombre a tu robot.', tip: '¿Limpia la casa? ¿Cuidan plantas? Hablar de él como de una persona es lo que lo vuelve personaje.' },
        ],
      },
    },
  },
  {
    id: 't15',
    slug: 'egg-carton-flower-garden',
    category: 'recycled',
    difficulty: 1,
    estimatedMinutes: 30,
    requiresPrinting: false,
    baseImage: 'assets/tutorials/egg-carton-flower-garden/base.webp',
    objectBox: { x: 0.14, y: 0.16, w: 0.72, h: 0.68 },
    materials: ['material.eggCarton', 'material.paint', 'material.glue', 'material.card'],
    steps: [
      { veil: 'full' },
      { veil: 'active', region: 'all' },
      { veil: 'active', region: 'centre' },
      { veil: 'active', region: 'bottom' },
      { veil: 'active', region: 'all' },
      { veil: 'active', region: 'left' },
      { veil: 'none' },
    ],
    copy: {
      pt: {
        title: 'Jardim de Flores',
        description: 'A embalagem de ovos vira um jardim inteiro, com flores, folhas e sol.',
        steps: [
          { instruction: 'Separe as conchinhas da embalagem, cortando rente.', tip: 'Conte as conchinhas antes: dá para saber quantas flores o jardim vai ter.' , safety: 'Cortar a embalagem com um adulto, com a tesoura apoiada na mesa.' },
          { instruction: 'Arredonde ou corte as pontas para virar pétalas.', tip: 'Quatro pontas da mesma altura deixam a flor com cara de margarida.' },
          { instruction: 'Pinte cada flor de uma cor.', tip: 'Duas cores na mesma flor, uma em cima da outra, fica bonito demais.' },
          { instruction: 'Pinte ou desenhe os caules.', tip: 'Um caule comprido e um curto juntos fazem o jardim parecer natural.' },
          { instruction: 'Cole as flores na folha do jardim.', tip: 'Apertar a conchinha por dentro segura a flor melhor do que cola.' },
          { instruction: 'Acrescente as folhas.', tip: 'Uma folha é um ovalinho com um risco no meio, e pronto.' },
          { instruction: 'Acrescente insetos ou um sol.', tip: 'Abelhas de recortar e colar dão vida ao jardim.' },
        ],
      },
      en: {
        title: 'Egg Carton Flower Garden',
        description: 'An egg carton turns into a whole garden, with flowers, leaves and sun.',
        steps: [
          { instruction: 'Cut the cups apart, cutting close to the edge.', tip: 'Count the cups first: it tells you how many flowers the garden will have.' , safety: 'Cut the carton with an adult, with the scissors resting on the table.' },
          { instruction: 'Round or snip the points to make petals.', tip: 'Four points of the same height make a daisy-like flower.' },
          { instruction: 'Paint each flower a colour.', tip: 'Two colours on one flower, one over the other, looks wonderful.' },
          { instruction: 'Paint or draw the stems.', tip: 'One long stem next to a short one makes the garden look natural.' },
          { instruction: 'Glue the flowers onto the garden page.', tip: 'Squeezing the cup from the inside holds the flower better than glue.' },
          { instruction: 'Add the leaves.', tip: 'A leaf is an oval with a line down the middle, and that is it.' },
          { instruction: 'Add insects or a sun.', tip: 'Cut-out bees bring the garden to life.' },
        ],
      },
      es: {
        title: 'Jardín de Flores',
        description: 'Una huevera se convierte en un jardín entero, con flores, hojas y sol.',
        steps: [
          { instruction: 'Separa las albicillas del cartón, cortando a ras.', tip: 'Cuenta las albicillas antes: sabrás cuántas flores tendrá el jardín.' , safety: 'Corta el cartón con un adulto, con las tijeras apoyadas en la mesa.' },
          { instruction: 'Redondea o corta las puntas para hacer pétalos.', tip: 'Cuatro puntas de la misma altura dan una flor parecida a una margarita.' },
          { instruction: 'Pinta cada flor de un color.', tip: 'Dos colores en la misma flor, uno encima del otro, queda precioso.' },
          { instruction: 'Pinta o dibuja los tallos.', tip: 'Un tallo largo junto a uno corto hace que el jardín parezca natural.' },
          { instruction: 'Pega las flores en la hoja del jardín.', tip: 'Apretar la albicilla por dentro sujeta la flor mejor que el pegamento.' },
          { instruction: 'Añade las hojas.', tip: 'Una hoja es un óvalo con una raya en el medio, y ya está.' },
          { instruction: 'Añade insectos o un sol.', tip: 'Abejas recortadas dan vida al jardín.' },
        ],
      },
    },
  },
  {
    id: 't16',
    slug: 'cereal-box-desk-organiser',
    category: 'recycled',
    difficulty: 2,
    estimatedMinutes: 35,
    requiresPrinting: false,
    baseImage: 'assets/tutorials/cereal-box-desk-organiser/base.webp',
    objectBox: { x: 0.18, y: 0.20, w: 0.64, h: 0.62 },
    materials: ['material.cerealBox', 'material.paper', 'material.tape', 'material.marker'],
    steps: [
      { veil: 'full' },
      { veil: 'active', region: 'all' },
      { veil: 'active', region: 'centre' },
      { veil: 'active', region: 'top' },
      { veil: 'active', region: 'all' },
      { veil: 'active', region: 'left' },
      { veil: 'none' },
    ],
    copy: {
      pt: {
        title: 'Organizador de Mesa',
        description: 'Uma caixa de cereal vira um organizador para lápis, pincel e tesoura.',
        steps: [
          { instruction: 'Marque com lápis a altura do organizador na caixa.', tip: 'Conte quantos lápis você quer guardar: a caixa precisa ser mais alta que eles.' },
          { instruction: 'Corte a caixa nessa marca, com um adulto.', tip: 'Segure a caixa com a mão que não corta, e corte com a lâmina virada para longe.' , safety: 'Cortar papelão grosso pede ajuda de um adulto.' },
          { instruction: 'Cubra tudo com papel colorido.', tip: 'A parte de dentro pode ficar sem cobrir: ninguém vai ver.' },
          { instruction: 'Faça uma frentezinha para colar o nome.', tip: 'Um retângulo de papel claro é onde vai o nome do dono.' },
          { instruction: 'Decore com desenhos e listras.', tip: 'Listras com a caneta e setas apontando para cada compartimento ajudam a achar as coisas.' },
          { instruction: 'Acrescente uma divisória no meio.', tip: 'A divisória é um cartão dobrado em dois, colado no fundo.' },
          { instruction: 'Encha com lápis e pincel.', tip: 'Guardar as coisas é a última etapa, e é a mais gostosa.' },
        ],
      },
      en: {
        title: 'Desk Organiser',
        description: 'A cereal box turns into an organiser for pencils, brushes and scissors.',
        steps: [
          { instruction: 'Mark the height of the organiser on the box with a pencil.', tip: 'Count how many pencils you want to keep: the box has to be taller than they are.' },
          { instruction: 'Cut the box at that mark, with an adult.', tip: 'Hold the box with the hand that is not cutting, and cut with the blade pointing away.' , safety: 'Cutting thick cardboard needs an adult.' },
          { instruction: 'Cover it all with coloured paper.', tip: 'The inside can stay bare: nobody will see it.' },
          { instruction: 'Add a front label area.', tip: 'A rectangle of pale paper is where the owner writes their name.' },
          { instruction: 'Decorate with drawings and stripes.', tip: 'Stripes drawn with a pen, and arrows pointing to each slot, make things easier to find.' },
          { instruction: 'Add a divider in the middle.', tip: 'The divider is a card folded in half and glued to the bottom.' },
          { instruction: 'Fill it with pencils and brushes.', tip: 'Putting the things away is the last step, and the nicest one.' },
        ],
      },
      es: {
        title: 'Organizador de Mesa',
        description: 'Una caja de cereales se convierte en un organizador para lápices, pinceles y tijeras.',
        steps: [
          { instruction: 'Marca con lápiz la altura del organizador en la caja.', tip: 'Cuenta cuántos lápices quieres guardar: la caja tiene que ser más alta que ellos.' },
          { instruction: 'Corta la caja en esa marca, con un adulto.', tip: 'Sujeta la caja con la mano que no corta y corta con la hoja hacia fuera.' , safety: 'Cortar cartón grueso pide ayuda de un adulto.' },
          { instruction: 'Cúbrelo todo con papel de colores.', tip: 'La parte de dentro puede quedar sin cubrir: nadie la va a ver.' },
          { instruction: 'Haz un cartelito delante para el nombre.', tip: 'Un rectángulo de papel claro es donde va el nombre del dueño.' },
          { instruction: 'Decora con dibujos y rayas.', tip: 'Rayas con el bolígrafo y flechas hacia cada compartment ayudan a encontrar las cosas.' },
          { instruction: 'Añade un separador en el medio.', tip: 'El separador es una tarjeta doblada por la mitad y pegada al fondo.' },
          { instruction: 'Llénalo con lápices y pinceles.', tip: 'Guardar las cosas es el último paso, y el más gustoso.' },
        ],
      },
    },
  },
  {
    id: 't17',
    slug: 'bottle-cap-mosaic',
    category: 'recycled',
    difficulty: 2,
    estimatedMinutes: 30,
    requiresPrinting: false,
    baseImage: 'assets/tutorials/bottle-cap-mosaic/base.webp',
    objectBox: { x: 0.16, y: 0.18, w: 0.68, h: 0.66 },
    materials: ['material.caps', 'material.card', 'material.glue', 'material.marker'],
    // Sete passos, como na spec: desenhar, separar, colocar, ajustar, colar o
    // meio, preencher a borda, contornar. O mosaico é um trabalho de forma
    // inteira, então quase todos os furos são 'all' — o que muda é o desenho
    // crescendo na tela conforme as tampinhas ganham lugar.
    steps: [
      { veil: 'full' },
      { veil: 'active', region: 'all' },
      { veil: 'active', region: 'all' },
      { veil: 'active', region: 'centre' },
      { veil: 'active', region: 'all' },
      { veil: 'active', region: 'all' },
      { veil: 'none' },
    ],
    copy: {
      pt: {
        title: 'Mosaico de Tampinhas',
        description: 'Tampinhas de plástico viram um desenho de cores, peça por peça.',
        steps: [
          { instruction: 'Desenhe no cartão um formato grande e simples.', tip: 'Coração, estrela, peixe ou casa. Formatos com muitas pontas dão trabalho.' },
          { instruction: 'Separe as tampinhas por cor.', tip: 'Montes de três cores já chegam para um desenho bonito.' },
          { instruction: 'Coloque as tampinhas sem cola e veja o desenho.', tip: 'Arrastar e trocar é de graça agora; depois da cola não dá para voltar atrás.' },
          { instruction: 'Ajuste o padrão até gostar.', tip: 'Alterne as cores em vez de agrupar: alternado fica mais bonito.' },
          { instruction: 'Cole só as tampinhas do meio primeiro.', tip: 'Começar pelo meio e ir para fora deixa sempre espaço para as bordas.' },
          { instruction: 'Preencha a parte de fora.', tip: 'As tampinhas da borda podem ficar tombadas para dentro, como um moldurinho.' },
          { instruction: 'Desenhe o contorno e os detalhes em volta.', tip: 'Uma linha grossa em volta do mosaico faz a figura aparecer.' },
        ],
      },
      en: {
        title: 'Bottle Cap Mosaic',
        description: 'Plastic caps turn into a picture made of colours, piece by piece.',
        steps: [
          { instruction: 'Draw a big simple shape on the card.', tip: 'A heart, a star, a fish or a house. Shapes with many points are hard work.' },
          { instruction: 'Sort the caps by colour.', tip: 'Three colours in three piles already make a nice picture.' },
          { instruction: 'Place the caps without glue and see the picture.', tip: 'Moving them around is free now; once the glue is on there is no going back.' },
          { instruction: 'Adjust the pattern until you like it.', tip: 'Alternate the colours instead of grouping them: alternating looks better.' },
          { instruction: 'Glue the middle caps on first.', tip: 'Starting in the middle and working outwards always leaves room for the edge.' },
          { instruction: 'Fill in the outside.', tip: 'Edge caps can lean inwards, like a border.' },
          { instruction: 'Draw the outline and the details around it.', tip: 'A thick line around the mosaic makes the shape show up.' },
        ],
      },
      es: {
        title: 'Mosaico de Tapones',
        description: 'Tapones de plástico se convierten en un dibujo de colores, pieza por pieza.',
        steps: [
          { instruction: 'Dibuja en el cartón una forma grande y sencilla.', tip: 'Un corazón, una estrella, un pez o una casa. Las formas con muchas puntas dan trabajo.' },
          { instruction: 'Separa los tapones por color.', tip: 'Tres colores en tres montones ya hacen un dibujo bonito.' },
          { instruction: 'Coloca los tapones sin pegamento y mira el dibujo.', tip: 'Moverlos es gratis ahora; después del pegamento no se puede volver atrás.' },
          { instruction: 'Ajusta el patrón hasta que te guste.', tip: 'Alterna los colores en vez de agruparlos: alternado queda mejor.' },
          { instruction: 'Pega primero solo los tapones del centro.', tip: 'Empezar por el centro y salir hacia fuera siempre deja sitio para el borde.' },
          { instruction: 'Rellena la parte de fuera.', tip: 'Los tapones del borde pueden inclinarse hacia dentro, como un marco.' },
          { instruction: 'Dibuja el contorno y los detalles alrededor.', tip: 'Una línea gruesa alrededor del mosaico hace que la forma aparezca.' },
        ],
      },
    },
  },
  {
    id: 't18',
    slug: 'cardboard-marble-maze',
    category: 'recycled',
    difficulty: 3,
    estimatedMinutes: 45,
    requiresPrinting: false,
    baseImage: 'assets/tutorials/cardboard-marble-maze/base.webp',
    objectBox: { x: 0.10, y: 0.12, w: 0.80, h: 0.76 },
    materials: ['material.box', 'material.cardboard', 'material.glue'],
    steps: [
      { veil: 'full' },
      { veil: 'active', region: 'all' },
      { veil: 'active', region: 'top' },
      { veil: 'active', region: 'left' },
      { veil: 'active', region: 'centre' },
      { veil: 'active', region: 'right' },
      { veil: 'none' },
    ],
    copy: {
      pt: {
        title: 'Labirinto de Papelão',
        description: 'Tiras de papelão coladas numa tampa de caixa viram um labirinto para a bolinha.',
        steps: [
          { instruction: 'Desenhe um caminho de labirinto na tampa da caixa.', tip: 'Um caminho só, sem bifurcações, é mais fácil de acertar na primeira vez.' },
          { instruction: 'Marque o começo e o fim.', tip: 'Um X e um círculo: o X é por onde a bolinha entra, o círculo é onde ela chega.' },
          { instruction: 'Corte as tiras curtas de papelão.', tip: 'Faixas de dois dedos de largura seguram a bolinha sem deixá-la passar.' , safety: 'Cortar papelão grosso pede ajuda de um adulto.' },
          { instruction: 'Cole as paredes em cima do caminho desenhado.', tip: 'Cole primeiro as curvas e depois as retas: é mais fácil acertar.' },
          { instruction: 'Acrescente dois becos sem saída.', tip: 'Beco sem saída é o que faz o labirinto ter graça.' },
          { instruction: 'Teste com a bolinha e ajuste.', tip: 'Onde a bolinha ficar presa, afaste a parede um pouquinho.' },
          { instruction: 'Brinque e cronometre quem chega antes.', tip: 'Cronometrar com o relógio do celular dá uma disputa de verdade.' , safety: 'A bolinha é uma peça pequena: fica longe de crianças pequenas.' },
        ],
      },
      en: {
        title: 'Cardboard Marble Maze',
        description: 'Cardboard strips glued into a box lid turn into a maze for the marble.',
        steps: [
          { instruction: 'Draw a maze route on the box lid.', tip: 'One single route with no branches is easier to get right the first time.' },
          { instruction: 'Mark the start and the finish.', tip: 'A cross and a circle: the cross is where the marble goes in, the circle is where it arrives.' },
          { instruction: 'Cut short strips of cardboard.', tip: 'Strips two fingers wide keep the marble in without letting it through.' , safety: 'Cutting thick cardboard needs an adult.' },
          { instruction: 'Glue the walls on top of the route you drew.', tip: 'Glue the curves first and the straight parts after: it is easier to line up.' },
          { instruction: 'Add two dead ends.', tip: 'Dead ends are what makes a maze fun.' },
          { instruction: 'Test with the marble and adjust.', tip: 'Where the marble gets stuck, move the wall out a little.' },
          { instruction: 'Play and time who arrives first.', tip: 'Timing with a phone clock turns it into a real contest.' , safety: 'The marble is a small part: keep it away from little siblings.' },
        ],
      },
      es: {
        title: 'Laberinto de Cartón',
        description: 'Tiras de cartón pegadas en una tapa de caja se vuelven un laberinto para la canica.',
        steps: [
          { instruction: 'Dibuja un camino de laberinto en la tapa de la caja.', tip: 'Un solo camino, sin bifurcaciones, es más fácil de acertar a la primera.' },
          { instruction: 'Marca el principio y el final.', tip: 'Una equis y un círculo: la equis es por donde entra la canica, el círculo es donde llega.' },
          { instruction: 'Corta tiras cortas de cartón.', tip: 'Tiras de dos dedos sujetan la canica sin dejarla pasar.' , safety: 'Cortar cartón grueso pide ayuda de un adulto.' },
          { instruction: 'Pega las paredes encima del camino dibujado.', tip: 'Pega primero las curvas y después las rectas: es más fácil de alinear.' },
          { instruction: 'Añade dos callejones sin salida.', tip: 'El callejón sin salida es lo que hace divertido el laberinto.' },
          { instruction: 'Prueba con la canica y ajusta.', tip: 'Donde la canica se atasque, separa un poco la pared.' },
          { instruction: 'Juega y cronometra quién llega antes.', tip: 'Cronometrar con el reloj del móvil convierte esto en una carrera de verdad.' , safety: 'La canica es una pieza pequeña: lejos de los hermanos pequeños.' },
        ],
      },
    },
  },
];
